[files]
extend-exclude = [
    "*.json",
    "*.js",
    "*.ipynb",
    "src/zenml/zen_stores/migrations/versions/",
    "tests/unit/materializers/test_built_in_materializer.py",
    "tests/integration/functional/cli/test_pipeline.py",
    "src/zenml/zen_server/dashboard/",
    "examples/llm_finetuning/lit_gpt/"
]

[default]
locale = "en-us"
