---
name: Lint
description: Lint TypeScript and Python code
runs:
  using: composite
  steps:
    - name: Install Node
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: 20.x
        cache: npm
        cache-dependency-path: package-lock.json
    - name: Install Node dependencies
      run: npm ci
      shell: bash
    - name: Check TypeScript format
      run: npm run format-check
      shell: bash
    - name: Install Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: '3.11'
    - name: Pip cache
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-lint-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-lint-
    - name: Install Python dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements-dev.txt
      shell: bash
    - name: Lint Python and YAML code
      run: ./scripts/lint.sh
      shell: bash
