---
name: Spellcheck
on: [pull_request]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          persist-credentials: false
      - name: Spell Check Repo
        uses: crate-ci/typos@cf5f1c29a8ac336af8568821ec41919923b05a83  # v1
